spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      username: userAdmin
      password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

  metrics:
    export:
      prometheus:
        enabled: true
  health:
    defaults:
      enabled: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    ROOT: ERROR